=== yuliaBiriukova/InetTech_Practices/InetTech_Practice1/xml/topics/topics.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://eng.grammar/entity/topic"
  	xmlns:eng="http://eng.grammar/entity/topic"
	xmlns:ent="http://eng.grammar/entity"
	elementFormDefault="qualified"
>
	<xsd:import namespace="http://eng.grammar/entity" schemaLocation="../entity/entity.xsd" />

	<xsd:element name="topics">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="topic" type="eng:Topic" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Topic">
		<xsd:complexContent>
			<xsd:extension base="ent:Entity">
				<xsd:all>
					<xsd:element name="levelId">
						<xsd:simpleType>
							<xsd:restriction base="xsd:integer">
								<xsd:minExclusive value="0"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="name">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:minLength value="2"/>
								<xsd:maxLength value="128"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="content">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:minLength value="2"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
				</xsd:all>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== yuliaBiriukova/InetTech_Practices/InetTech_Practice1/xml/topics/topics.xml
<?xml version="1.0" encoding="utf-8" ?>
<topics xmlns="http://eng.grammar/entity/topic"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://eng.grammar/entity/topic topics.xsd"
>
	<topic id="1" version="1">
		<levelId>1</levelId>
		<name>Nouns</name>
		<content>
			Nouns are words that we use to name people, places, things, and ideas. Nouns have singular(one) and plural(more than one) forms. There are two types of nouns: common(book, dog) and proper nouns (London, John).
		</content>
	</topic>
	<topic id="2" version="1">
		<levelId>1</levelId>
		<name>Pronouns</name>
		<content>
			Pronouns are words that replace nouns in sentences. They help avoid repeating the same nouns, making sentences clearer and more concise.
			Pronouns: I, you, we, they, he, she, it.
		</content>
	</topic>
	<topic id="3" version="1">
		<levelId>1</levelId>
		<name>Verbs: Regular, Irregular</name>
		<content>
			Verbs are action words that show what someone or something is doing. Verbs types: regular, irregular. 
			Regular verbs follow a pattern when changing tenses, usually by adding "-ed" to the base form to form the past tense.
			Irregular verbs don't follow a regular pattern when changing tenses. Their forms change in unique ways.
		</content>
	</topic>
	<topic id="4" version="1">
		<levelId>2</levelId>
		<name>Present Simple Tense</name>
		<content>
			The Present Simple Tense is used to talk about things that happen regularly or facts that are always true.
			Formation: I, you, we, they + verb. He, she, it + verb + "-s/-es".
			We use Present Simple for habits, general truths, scheduled actions.
		</content>
	</topic>
	<topic id="5" version="1">
		<levelId>2</levelId>
		<name>Present Continuous Tense</name>
		<content>
			We use the Present Continuous Tense to talk about actions happening now, at the moment of speaking.
			Formation: to be + verb + "-ing"
			We use Present Continious for actions happening now, planned actions, repeated actions, story-telling.
		</content>
	</topic>
	<topic id="6" version="1">
		<levelId>2</levelId>
		<name>Past Simple Tense</name>
		<content>
			The Past Simple Tense is used to talk about completed acrions in the past.
			Formation: verb + "-ed" (reqular verbs),  2nd form of the verb (irregular verbs).
		</content>
	</topic>
</topics>
