=== yuliaBiriukova/InetTech_Practices/InetTech_Practice1/static/xml/completedTopics/completedTopics.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://eng.grammar/entity/completedTopic"
  	xmlns:eng="http://eng.grammar/entity/completedTopic"
	xmlns:ent="http://eng.grammar/entity"
	elementFormDefault="qualified"
>
	<xsd:import namespace="http://eng.grammar/entity" schemaLocation="../entity/entity.xsd" />

	<xsd:element name="completedTopics">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="completedTopic" type="eng:CompletedTopic" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="CompletedTopic">
		<xsd:complexContent>
			<xsd:extension base="ent:Entity">
				<xsd:all>
					<xsd:element name="topicId">
						<xsd:simpleType>
							<xsd:restriction base="xsd:integer">
								<xsd:minExclusive value="0"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="userId">
						<xsd:simpleType>
							<xsd:restriction base="xsd:integer">
								<xsd:minExclusive value="0"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="percentage">
						<xsd:simpleType>
							<xsd:restriction base="xsd:integer">
								<xsd:minInclusive value="0"/>
								<xsd:maxInclusive value="100"/>
								<xsd:totalDigits value="3"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
				</xsd:all>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
</xsd:schema>

=== yuliaBiriukova/InetTech_Practices/InetTech_Practice1/static/xml/completedTopics/completedTopics.xml
<?xml version="1.0" encoding="utf-8" ?>
<completedTopics xmlns="http://eng.grammar/entity/completedTopic"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://eng.grammar/entity/completedTopic completedTopics.xsd"
>
	<completedTopic id="1">
		<topicId>3</topicId>
		<userId>1</userId>
		<percentage>100</percentage>
	</completedTopic>
	<completedTopic id="2">
		<topicId>4</topicId>
		<userId>1</userId>
		<percentage>66</percentage>
	</completedTopic>
	<completedTopic id="3">
		<topicId>5</topicId>
		<userId>1</userId>
		<percentage>50</percentage>
	</completedTopic>
	<completedTopic id="1">
		<topicId>3</topicId>
		<userId>2</userId>
		<percentage>100</percentage>
	</completedTopic>
	<completedTopic id="2">
		<topicId>4</topicId>
		<userId>2</userId>
		<percentage>33</percentage>
	</completedTopic>
	<completedTopic id="3">
		<topicId>5</topicId>
		<userId>2</userId>
		<percentage>100</percentage>
	</completedTopic>
</completedTopics>
