=== yuliaBiriukova/InetTech_Practices/InetTech_Practice1/xml/levels/levels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://eng.grammar/entity/level"
  	xmlns:eng="http://eng.grammar/entity/level"
	xmlns:ent="http://eng.grammar/entity" 
	elementFormDefault="qualified"
>
	<xsd:import namespace="http://eng.grammar/entity" schemaLocation="../entity/entity.xsd" />
	
	<xsd:element name="levels">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="level" type="eng:Level" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="Level">
		<xsd:complexContent>
			<xsd:extension base="ent:Entity">
				<xsd:all>
					<xsd:element name="code">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:length value="2"/>
								<xsd:pattern value="^[A-C][1-2]$"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
					<xsd:element name="name">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:minLength value="2"/>
								<xsd:maxLength value="100"/>
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:element>
				</xsd:all>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
</xsd:schema>

=== yuliaBiriukova/InetTech_Practices/InetTech_Practice1/xml/levels/levels.xml
<?xml version="1.0" encoding="utf-8" ?>
<levels xmlns="http://eng.grammar/entity/level"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://eng.grammar/entity/level levels.xsd"
>
	<level id="1">
		<code>A1</code>
		<name>Beginner</name>
	</level>
	<level id="2">
		<code>A2</code>
		<name>Pre-Intermediate</name>
	</level>
	<level id="3">
		<code>B1</code>
		<name>Intermediate</name>
	</level>
	<level id="4">
		<code>B2</code>
		<name>Upper-Intermediate</name>
</level>
	<level id="5">
		<code>C1</code>
		<name>Advanced</name>
	</level>
</levels>
